spring.application.name=mobile

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mobilecare
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/mobilecare
spring.datasource.username=root #default mysql usename if required please change 
spring.datasource.password=your password 
#spring.datasource.password=mobilecare
spring.datasource.datebase_name=mobilecare
spring.datasource.backuplocation=C://Backups/backup.sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true

# Hibernate Configuration (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
management.endpoints.web.exposure.include=*
server.port=8011
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
current.date=#{T(java.time.LocalDate).now()}
#camunda.bpm.deployment-resource-pattern=classpath*:**/*.bpmn,classpath*:**/*.form
logging.level.org.camunda.bpm.spring.boot=DEBUG
management.endpoint.health.show-details=always


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arylyte@gmail.com
spring.mail.password=dlwvfkzbsnyansoi

<<<<<<< HEAD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
=======
management.endpoint.health.show-details=always
>>>>>>> 6fda1b38b313df946104d4e3df6a6b56750d6df4
