package org.camunda.service.impl;

import org.camunda.entity.Employee;
import org.camunda.service.MailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.io.UnsupportedEncodingException;

@Service
public class MailServiceImpl {

    @Autowired
    private JavaMailSender mailSender;


    @Autowired
    private MailService mailService;

    public void sendMail(String to, String subject) throws MessagingException, UnsupportedEncodingException {
        Employee employee = mailService.getSenderEmailDetails("nasir");
        String body="<!DOCTYPE html> <html> <head> <meta charset='UTF-8'> </head> " +
                "<body style='font-family: Arial, Helvetica, sans-serif; background-color:#f4f6f9;'> " +
                "<table width='100%' cellspacing='0' cellpadding='0'> <tr> <td align='center'> " +
                "<table width='650' cellpadding='0' cellspacing='0' style='background:#ffffff;border:1px solid #dcdcdc;'>" +
                "<tr> " +
                    " <td style='background:#0d6efd;color:white;padding:20px;text-align:center;'> " +
                "<h2>Employee Onboarding Workflow</h2> </td> </tr>  " +
                "<tr> <td style='padding:20px;'> " +
                "<p>Dear <b>${userName}</b>,</p> " +
                "<p> A new employee onboarding task has been assigned to you. " +
                "Please review the employee details and complete the task. </p> " +
                "<table width='100%' cellpadding='8' style='border-collapse:collapse;border:1px solid #ddd;'>" +
                " <tr style='background:#f2f2f2;'> <td><b>Employee ID</b></td> " +
                "<td>${employeeId}</td>" +
                " </tr> " +
                "<tr> <td><b>Employee Name</b></td> <td>"+employee.getEmployeeName()+"</td> </tr>" +
                "<tr style='background:#f2f2f2;'> <td><b>Designation</b></td> <td>"+employee.getDesignation()+"</td> </tr> " +
                "<tr> <td><b>Department</b></td> <td>"+employee.getDepartment()+"</td> </tr> " +
                "<tr style='background:#f2f2f2;'> <td><b>Current Stage</b></td> <td></td> </tr> " +
               // "<tr> <td><b>Assigned To</b></td> <td>${assignee}</td> </tr> <" +
                "/table> <br> <div style='text-align:center;'> " +
                "<a href='http://localhost:4200' style='background:#0d6efd; color:white; text-decoration:none; padding:12px 25px; border-radius:5px; display:inline-block;'> Open Employee Onboarding </a> </div> <br> <p> <b>Note:</b> This is an automated email generated by the Employee Onboarding Workflow Platform. </p> <p> Regards,<br> Employee Onboarding Workflow Team </p> </td> </tr>  <tr> <td style='background:#f2f2f2; text-align:center; padding:15px; font-size:12px; color:#666;'> © 2026 Employee Onboarding Workflow Platform </td> </tr> </table> </td> </tr> </table> </body> </html>";
       /*
       SimpleMailMessage message = new SimpleMailMessage();
        message.setTo(toMail);
        message.setSubject("Task Created for Review");
        */

        MimeMessage mimemessage = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(mimemessage, true, "UTF-8");
        helper.setText(body, true);

        helper.setTo(employee.getEmail());
        helper.setSubject("Employee Onboarding Notification");
        helper.setFrom(new InternetAddress(
                "arylyte@gmail.com",
                "Employee Onboarding Workflow"
        ));
        mailSender.send(mimemessage);
    }

}
