---
server:
  port: 8095
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          cors:
            mappings:
              "[/**]":
                allowedOrigins: http://localhost:4200
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          management:
            endpoints:
              web:
                exposure:
                  include: "*"
          routes:
            - id: auth-service
              uri: http://localhost:8089
              predicates:
                - Path=/auth/**
            - id: employee-service
              uri: http://localhost:8089
              predicates:
                - Path=/emp/**,/user/**
            - id: camunda-service
              uri: http://localhost:8011
              predicates:
                - Path=/tasks/**,/process/**,/history/**,/mail/**,/group/**
